curl -v -X POST http://climateguard-360.local:8080/insert_data.php \
    -d "station_id=00:1A:22:33:44:55" \
    -d "temperature=22.5" \
    -d "humidity=45.2" \
    -d "pressure=1013.25" \
    -d "light_intensity=300" \
    -d "air_quality=500" \
    -d "rain=0" \
    -d "station_name=TestStation" \
    -d "station_description=TestDescription" \
    -d "station_mode=Outdoor"
